all:
	cmake -S llvm -B build -DLLVM_ENABLE_RTTI=FALSE -DLLVM_TARGETS_TO_BUILD=VCSIR -DLLVM_ENABLE_PROJECTS="lld;clang" -DLLVM_INCLUDE_UTILS=TRUE -DLLVM_INCLUDE_TESTS=TRUE -DLLVM_INCLUDE_BENCHMARKS=FALSE -DLLVM_CCACHE_BUILD=ON -DCMAKE_BUILD_TYPE=Debug
	cmake --build build -t llc
